# filecombinator/_version.py
# file generated by setuptools_scm
# don't change, don't track in version control
from typing import TYPE_CHECKING  # pragma: no cover

if TYPE_CHECKING:  # pragma: no cover
    from typing import Tuple, Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object  # pragma: no cover

version: str  # pragma: no cover
__version__: str  # pragma: no cover
__version_tuple__: VERSION_TUPLE  # pragma: no cover
version_tuple: VERSION_TUPLE  # pragma: no cover

__version__ = version = "0.3.0.post0"  # pragma: no cover
__version_tuple__ = version_tuple = (0, 3, 0)  # pragma: no cover
